spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ticket_db
    username: ticket_user
    password: ticket_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6380
      password: ticket_redis_pass
  mail:
    host: localhost
    port: 1025 # Default Mailhog port
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day in ms
  refresh-expiration: 604800000 # 7 days in ms

server:
  port: 8080
